# Generated by Django 4.1.2 on 2022-10-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_student_customuser_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='users/custom_user/icon/', verbose_name='アイコン'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='introduction',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='自己紹介文'),
        ),
    ]
